CREATE ROLE HEVO_ROLE;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE HEVO_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE HEVO_DB TO ROLE HEVO_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HEVO_DB TO ROLE HEVO_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
ON ALL SCHEMAS IN DATABASE HEVO_DB TO ROLE HEVO_ROLE;

GRANT ROLE HEVO_ROLE TO USER TRIPTI098;
